experimentName: G--G BGRL on IMDB-MULTI
searchSpace:
  learning_rate:
    _type: choice
    _value: [0.1, 0.01, 0.001, 0.0005, 0.0001]
  weight_decay:
    _type: choice
    _value: [0.001, 0.0001, 0.00001, 0.000001, 0.0000001, 0.00000001, 0.000000001]
  num_epochs:
    _type: choice
    _value: [100, 200, 300, 500, 800, 1000, 1200, 1500, 1800, 2000]
  hidden_dim:
    _type: choice
    _value: [32, 64, 128, 256, 512]
  proj_dim:
    _type: choice
    _value: [32, 64, 128, 256, 512]
  num_layers:
    _type: choice
    _value: [2, 3, 4, 5, 6]
  activation:
    _type: choice
    _value: ["relu", "hardtanh", "elu", "leakyrelu", "prelu", "rrelu"]
  augmentor1:drop_node_prob:
    _type: choice
    _value: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  augmentor2:drop_node_prob:
    _type: choice
    _value: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  augmentor1:drop_feat_prob:
    _type: choice
    _value: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  augmentor2:drop_feat_prob:
    _type: choice
    _value: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  # obj:infonce:tau:
  #   _type: choice
  #   _value: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
trialCommand: python train_graph_BGRL_g2g.py --dataset IMDB-MULTI --param_path nni
trialCodeDirectory: .
trialGpuNumber: 1
trialConcurrency: 8
maxExperimentDuration: 72h
maxTrialNumber: 10000
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True
  gpuIndices: 0,1,2,3,4,5,6,7